on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: >
          docker build -t ${{ github.event.repository.name }}:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Remove old container
        run: docker rm -f ${{ github.event.repository.name }}

      - name: Run a command inside the container
        run: docker run -d -p 5000:80 --name ${{ github.event.repository.name }} ${{ github.event.repository.name }}:latest